site_name: BoltRing Documentation
site_description: 'Bitcoin Lightning Contactless NFC Payment Ring Documentation'
copyright: "Copyright &copy; 2023 The Bitcoin BoltRing Team"
site_author: 'Titusz Pan'
site_url: 'https://docs.bolt-ring.com'

# Repository
repo_name: 'bitcoin-ring/boltring-docs'
repo_url: 'https://github.com/bitcoin-ring/boltring-docs'
edit_uri: 'edit/main/docs/'

extra_css:
  - css/styles.css

theme:
  name: material
  language: en
  favicon: images/favicon.png
  icon:
    logo: fontawesome/brands/bitcoin
  palette:
    primary: deep orange
    accent: green
  features:
    - navigation.tracking
    - navigation.expand
    - navigation.footer
    - toc.follow
extra:
  social:
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/bitcoin_ring
    - icon: fontawesome/brands/github
      link: https://github.com/bitcoin-ring
    - icon: fontawesome/solid/cart-shopping
      link: https://bitcoin-ring.com
plugins:
  - search
  - glightbox

markdown_extensions:
  - attr_list
  - md_in_html
  - admonition
  - footnotes
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.snippets
  - pymdownx.magiclink
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - abbr

nav:
  - Introduction: index.md
  - Merchant Compatibility: merchant-compatibility.md
  - Getting Started: getting-started.md
  - Setup Guides:
    - LNbits: lnbits.md
